# Generated by Django 3.1.4 on 2020-12-27 20:21

import Job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=Job.models.image_upload),
        ),
    ]
