# Generated by Django 3.1.4 on 2020-12-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
